### ISSUE TITLE
Wrong repository and missed dependencies in 10.2 POM

### ISSUE THREAD

**Issue by xvik** [rnveach/checkstyle-backport-jre8#8]
There is a mistake in the documentation site: actual repository url is `http://rnveach.github.io/checkstyle-backport-jre8/` and not `http://rnveach.github.io/checkstyle-backport-jre8/maven2`.

More importantly, since version 10.2 pom miss required dependencies (like guava) which makes checkstyle fail with

```
Caused by: java.lang.ClassNotFoundException: com.google.common.reflect.ClassPath
```

Compare version [10.1 pom](https://rnveach.github.io/checkstyle-backport-jre8/com/puppycrawl/tools/checkstyle-backport-jre8/10.1/checkstyle-backport-jre8-10.1.pom) and [10.3.1 pom](https://rnveach.github.io/checkstyle-backport-jre8/com/puppycrawl/tools/checkstyle-backport-jre8/10.3.1/checkstyle-backport-jre8-10.3.1.pom).

I know there is a shaded jar published and I have to use it instead (and it works fine)

**Comment by xvik** [comment]
Thank you for repository fix, I switched to the new url.

> Guava is listed in the POM even now.
https://github.com/rnveach/checkstyle-backport-jre8/blob/master/pom.xml#L108

Yes, dependencies are present in project pom, but they are absent in the [published pom](https://rnveach.github.io/checkstyle-backport-jre8/maven2/com/puppycrawl/tools/checkstyle-backport-jre8/10.3.1/checkstyle-backport-jre8-10.3.1.pom) (only test-scoped dependencies remains; compare it with the [original checkstyle pom](https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/10.3.1/checkstyle-10.3.1.pom))

> I would need further information to assist with this, like how you are running backport.

It woldn't help much, but I use it in gradle through gradle's checkstyle plugin. More specifically, I'm the author of [gradle-quality-plugin](https://github.com/xvik/gradle-quality-plugin) and I use your backport for an [automatic fallback under java 8](https://github.com/xvik/gradle-quality-plugin/blob/master/src/main/groovy/ru/vyarus/gradle/plugin/quality/QualityPlugin.groovy#L145) in my plugin.

It would be more preferrable to not use shaded jar version (not 'all') simply because it allows caching third party dependencies. "All" jar weights ~15 mb whereas pure checkstyle weights only 1.9 mb and, after checkstyle version update, user would not need to download everything again. It's not critical ofc., but still an optimization.

**Comment by rnveach** [comment]
> Yes, dependencies are present in project pom, but they are absent in the [published pom](https://rnveach.github.io/checkstyle-backport-jre8/maven2/com/puppycrawl/tools/checkstyle-backport-jre8/10.3.1/checkstyle-backport-jre8-10.3.1.pom)

https://www.diffnow.com/compare-urls
https://raw.githubusercontent.com/rnveach/checkstyle-backport-jre8/gh-pages/maven2/com/puppycrawl/tools/checkstyle-backport-jre8/10.3.1/checkstyle-backport-jre8-10.3.1.pom
https://repo1.maven.org/maven2/com/puppycrawl/tools/checkstyle/10.3.1/checkstyle-10.3.1.pom

I see what your saying now. All the dependencies are completely gone. Something happened starting with 10.2 . It wasn't an issue in 10.1 .

My deploy command is basically `clean package -Passembly deploy -e` with me supplying `cs.maven.directory` and some skips for pmd, findbugs, cobertura, jacoco, forbiddenapis, and tidy.

10.2 is when I started having issues deploying and had to skip tidy to bypass it to get it to work and do a deploy. That is my guess as to what the issue is, but I am not fully sure.

I tried removing the skip and tidy still fails and I could not figure out what the issue is, since it doesn't happen in main checkstyle until my deploy commit is added ( https://github.com/rnveach/checkstyle-backport-jre8/commit/7032abdb5ec9d48e9e61079625bd8c7f547f4dd5 ).
````
Caused by: org.apache.maven.plugin.MojoFailureException: The POM violates the code style. Please format it by running `mvn tidy:pom`.
	at org.codehaus.mojo.tidy.CheckMojo.executeForPom(CheckMojo.java:42)
	at org.codehaus.mojo.tidy.TidyMojo.execute(TidyMojo.java:78)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
````
But `mvn tidy:pom` passed without doing anything or modifying anything.

**Comment by xvik** [comment]
Thank you very much! Works perectly!
